"use client";

import {
  Palette,
  Video,
  Zap,
  Image,
  PenTool,
  Layers,
  Code,
  Globe,
  Smartphone,
  ShoppingCart,
  Rocket,
  FileText,
  PenSquare,
  BookOpen,
  MessageSquare,
  FileEdit,
  Brain,
  Database,
  BarChart3,
  Cpu,
  Network,
  TrendingUp,
  Search,
  Share2,
  Target,
  Mail,
  BarChart,
  Gamepad2,
  Puzzle,
  Users,
  Trophy,
  type LucideIcon,
} from "lucide-react";
import type { ServiceIconName } from "@/lib/services-data";

const SERVICE_ICONS: Record<ServiceIconName, LucideIcon> = {
  palette: Palette,
  video: Video,
  zap: Zap,
  image: Image,
  penTool: PenTool,
  layers: Layers,
  code: Code,
  globe: Globe,
  smartphone: Smartphone,
  shoppingCart: ShoppingCart,
  rocket: Rocket,
  fileText: FileText,
  penSquare: PenSquare,
  bookOpen: BookOpen,
  messageSquare: MessageSquare,
  fileEdit: FileEdit,
  brain: Brain,
  database: Database,
  barChart3: BarChart3,
  cpu: Cpu,
  network: Network,
  trendingUp: TrendingUp,
  search: Search,
  share2: Share2,
  target: Target,
  mail: Mail,
  barChart: BarChart,
  gamepad2: Gamepad2,
  puzzle: Puzzle,
  users: Users,
  trophy: Trophy,
};

export function getServiceIcon(name: ServiceIconName): LucideIcon {
  return SERVICE_ICONS[name];
}
